#!/usr/bin/env python3
"""
LOCAL Script 2: Fetch 90-Day Trade Data for Top Items

This script:
1. Reads the top_items.json file generated by Script 1
2. Fetches 90-day trade data for the top 50 items
3. Applies the same volatility-aware averaging (but with 90d window)
4. Generates the final trade_cache.json for upload to GitHub

Volatility Logic (same as Script 1):
- Time windows: 1h, 7d, 90d (instead of 30d)
- Same threshold and minimum trades requirement
- Outputs data in the exact format expected by trade_economics_analysis.py

Run this script locally AFTER Script 1 completes.
"""

import aiohttp
import asyncio
import json
import sys
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import numpy as np

# Configuration
API_URL = "https://hqxg0u8s64.execute-api.ca-central-1.amazonaws.com/Production/tradingpost"
RATE_LIMIT_DELAY = 0  # No delay - API is fast with no limits
MAX_PAGES_PER_ITEM = 100
MAX_DAYS_HISTORY = 90  # 90-day window for final data

# Volatility thresholds (will be loaded from Script 1 output)
MIN_TRADES_THRESHOLD = 5

# File paths
SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR / "data"
CACHE_DIR = SCRIPT_DIR / "cache"
TOP_ITEMS_FILE = DATA_DIR / "top_items.json"
OUTPUT_TRADE_CACHE = DATA_DIR / "trade_cache.json"


class VolatilityAware90dFetcher:
    """Fetches 90-day data with volatility-aware averaging (ASYNC)."""

    def __init__(self, threshold: float):
        self.threshold = threshold

    async def fetch_item_trades(self, session: aiohttp.ClientSession, item_name: str,
                                max_days: int = MAX_DAYS_HISTORY) -> List[Dict]:
        """
        Fetch all trades for a specific item within the 90-day window (ASYNC).

        Args:
            session: aiohttp session
            item_name: Name of the item to fetch
            max_days: Maximum age of trades to fetch (in days)

        Returns:
            List of trade records
        """
        all_trades = []
        page = 1
        cutoff_date = datetime.now() - timedelta(days=max_days)

        while page <= MAX_PAGES_PER_ITEM:
            try:
                params = {
                    "search_text": item_name,
                    "page": page
                }

                async with session.get(API_URL, params=params, timeout=aiohttp.ClientTimeout(total=10)) as response:
                    if response.status != 200:
                        break

                    data = await response.json()

                    if not data or len(data) == 0:
                        break

                    # Filter trades within time window
                    page_has_recent_trades = False
                    for trade in data:
                        try:
                            trade_time = datetime.strptime(trade['time'], "%Y-%m-%d %H:%M:%S.%f")

                            if trade_time >= cutoff_date:
                                page_has_recent_trades = True
                                all_trades.append(trade)
                        except (ValueError, KeyError):
                            all_trades.append(trade)
                            page_has_recent_trades = True

                    if not page_has_recent_trades:
                        break

                    page += 1

            except Exception as e:
                break

        return all_trades

    def calculate_all_windows_at_once(self, trades: List[Dict]) -> Dict:
        """
        Calculate ALL time window averages in a SINGLE pass for efficiency.
        Parses timestamps once and calculates 1h, 7d, 90d in one iteration.

        Args:
            trades: List of trade records

        Returns:
            Dict with window stats for 1h, 7d, 90d
        """
        if not trades:
            return {
                '1h': {'price': 0.0, 'trades': 0},
                '7d': {'price': 0.0, 'trades': 0},
                '90d': {'price': 0.0, 'trades': 0}
            }

        now = datetime.now()
        cutoff_1h = now - timedelta(hours=1)
        cutoff_7d = now - timedelta(days=7)

        # Single pass through all trades - parse timestamp once
        prices_1h = []
        prices_7d = []
        prices_all = []

        for trade in trades:
            try:
                # Parse timestamp ONCE
                trade_time = datetime.strptime(trade['time'], "%Y-%m-%d %H:%M:%S.%f")
                amount = trade['amount']
                price = trade['price']

                if amount <= 0:
                    continue

                price_per_unit = price / amount

                # Add to appropriate windows
                if trade_time >= cutoff_1h:
                    prices_1h.append(price_per_unit)
                if trade_time >= cutoff_7d:
                    prices_7d.append(price_per_unit)
                prices_all.append(price_per_unit)

            except (ValueError, KeyError, ZeroDivisionError):
                continue

        # Calculate medians
        avg_1h = float(np.median(prices_1h)) if len(prices_1h) >= MIN_TRADES_THRESHOLD else 0.0
        avg_7d = float(np.median(prices_7d)) if len(prices_7d) >= MIN_TRADES_THRESHOLD else 0.0
        avg_all = float(np.median(prices_all)) if len(prices_all) >= MIN_TRADES_THRESHOLD else 0.0

        return {
            '1h': {'price': avg_1h, 'trades': len(prices_1h)},
            '7d': {'price': avg_7d, 'trades': len(prices_7d)},
            '90d': {'price': avg_all, 'trades': len(prices_all)}
        }

    def calculate_volatility_aware_price(self, trades: List[Dict], item_name: str) -> Tuple[float, str, Dict]:
        """
        Determine the best average price using volatility-aware logic.
        Optimized: calculates all windows in ONE pass instead of three.

        Args:
            trades: List of trade records
            item_name: Name of the item (for logging)

        Returns:
            Tuple of (best_price, window_used, window_stats)
        """
        # Calculate ALL windows at once (single pass)
        window_stats = self.calculate_all_windows_at_once(trades)

        avg_1h = window_stats['1h']['price']
        count_1h = window_stats['1h']['trades']
        avg_7d = window_stats['7d']['price']
        count_7d = window_stats['7d']['trades']
        avg_90d = window_stats['90d']['price']
        count_90d = window_stats['90d']['trades']

        # DECISION TREE - If insufficient trades in 1h window
        if count_1h < MIN_TRADES_THRESHOLD:
            if count_7d < MIN_TRADES_THRESHOLD:
                return avg_90d, '90d (fallback)', window_stats
            else:
                return avg_7d, '7d (no recent)', window_stats

        # Check volatility
        if avg_90d > 0:
            diff_1h_90d = abs(avg_1h - avg_90d) / avg_90d * 100
        else:
            diff_1h_90d = 0

        # Item is NOT volatile - use 90d average
        if diff_1h_90d <= self.threshold:
            return avg_90d, '90d (stable)', window_stats

        # Item IS volatile - choose between 1h and 7d
        if count_7d < MIN_TRADES_THRESHOLD:
            return avg_1h, '1h (volatile, no 7d)', window_stats

        # Compare 1h vs 7d
        if avg_7d > 0:
            diff_1h_7d = abs(avg_1h - avg_7d) / avg_7d * 100
        else:
            diff_1h_7d = 0

        if diff_1h_7d > self.threshold:
            return avg_1h, '1h (volatile spike)', window_stats
        else:
            return avg_7d, '7d (volatile stable)', window_stats


class FinalDataGenerator:
    """Generates final 90-day trade cache for GitHub upload."""

    def __init__(self):
        self.timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

        # Create cache directory
        CACHE_DIR.mkdir(exist_ok=True)

    def load_top_items(self) -> Tuple[List[str], float]:
        """Load top items list from Script 1 output."""
        print(f"\n{'='*80}")
        print(f"LOADING TOP ITEMS FROM SCRIPT 1")
        print(f"{'='*80}")

        if not TOP_ITEMS_FILE.exists():
            raise FileNotFoundError(f"{TOP_ITEMS_FILE} not found. Run local_fetch_30d_analysis.py first.")

        with open(TOP_ITEMS_FILE, 'r') as f:
            data = json.load(f)

        item_names = data['top_items']
        threshold = data['metadata'].get('volatility_threshold_pct', 20.0)

        print(f"✓ Top items loaded: {len(item_names)}")
        print(f"✓ Volatility threshold: {threshold:.1f}%")
        print(f"{'='*80}\n")

        return item_names, threshold

    async def fetch_90d_data(self, item_names: List[str], threshold: float) -> Tuple[List[Dict], Dict]:
        """Fetch 90-day trade data for all top items (ASYNC - CONCURRENT)."""
        fetcher = VolatilityAware90dFetcher(threshold)

        total_items = len(item_names)
        print(f"\n{'='*80}")
        print(f"FETCHING 90-DAY TRADE DATA FOR TOP ITEMS (CONCURRENT)")
        print(f"{'='*80}")
        print(f"Items to fetch: {total_items}")
        print(f"Concurrent requests: ALL AT ONCE")
        print(f"Estimated time: 5-15 seconds (blazing fast!)")
        print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"{'='*80}\n")

        # Create async session and fetch ALL items concurrently
        async with aiohttp.ClientSession() as session:
            tasks = []

            for item_name in item_names:
                task = fetcher.fetch_item_trades(session, item_name, max_days=MAX_DAYS_HISTORY)
                tasks.append((item_name, task))

            # Execute all requests concurrently
            print(f"  Launching {total_items} concurrent requests...")
            results = await asyncio.gather(*[task for _, task in tasks])

            # Process results
            all_trades = []
            fetch_results = {}

            for (item_name, _), trades in zip(tasks, results):
                all_trades.extend(trades)
                fetch_results[item_name] = {
                    'trades': trades,
                    'trade_count': len(trades)
                }
                print(f"  ✓ {item_name}: {len(trades)} trades")

        print(f"\n{'='*80}")
        print(f"FETCH COMPLETE")
        print(f"{'='*80}")
        print(f"Items fetched: {total_items}")
        print(f"Items with trades: {sum(1 for r in fetch_results.values() if r['trade_count'] > 0)}")
        print(f"Total trades: {len(all_trades):,}")
        print(f"Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"{'='*80}\n")

        return all_trades, fetch_results

    def apply_volatility_analysis(self, fetch_results: Dict, threshold: float) -> Dict:
        """Apply volatility-aware averaging to 90d data."""
        print(f"\n{'='*80}")
        print(f"APPLYING VOLATILITY-AWARE AVERAGING (90d)")
        print(f"{'='*80}")
        print(f"Threshold: {threshold:.1f}%")
        print(f"Minimum trades per window: {MIN_TRADES_THRESHOLD}")
        print(f"{'='*80}\n")

        fetcher = VolatilityAware90dFetcher(threshold)
        analysis_stats = {
            'window_usage': {'1h': 0, '7d': 0, '90d': 0},
            'total_analyzed': 0,
            'insufficient_data': 0
        }

        item_analysis = {}

        for item_name, result in fetch_results.items():
            trades = result['trades']

            if len(trades) < MIN_TRADES_THRESHOLD:
                analysis_stats['insufficient_data'] += 1
                continue

            # Calculate volatility-aware price
            best_price, window_used, window_stats = fetcher.calculate_volatility_aware_price(
                trades, item_name
            )

            if best_price == 0:
                analysis_stats['insufficient_data'] += 1
                continue

            analysis_stats['total_analyzed'] += 1

            # Track window usage
            if '1h' in window_used:
                analysis_stats['window_usage']['1h'] += 1
            elif '7d' in window_used:
                analysis_stats['window_usage']['7d'] += 1
            elif '90d' in window_used:
                analysis_stats['window_usage']['90d'] += 1

            item_analysis[item_name] = {
                'best_price': best_price,
                'window_used': window_used,
                'window_stats': window_stats
            }

        print(f"90d Analysis Summary:")
        print(f"  Items analyzed: {analysis_stats['total_analyzed']}")
        print(f"  Items with insufficient data: {analysis_stats['insufficient_data']}")
        print(f"\n  Window Usage:")
        print(f"    1h window: {analysis_stats['window_usage']['1h']} items ({analysis_stats['window_usage']['1h']/max(1,analysis_stats['total_analyzed'])*100:.1f}%)")
        print(f"    7d window: {analysis_stats['window_usage']['7d']} items ({analysis_stats['window_usage']['7d']/max(1,analysis_stats['total_analyzed'])*100:.1f}%)")
        print(f"    90d window: {analysis_stats['window_usage']['90d']} items ({analysis_stats['window_usage']['90d']/max(1,analysis_stats['total_analyzed'])*100:.1f}%)")
        print(f"{'='*80}\n")

        return item_analysis, analysis_stats

    def save_final_cache(self, all_trades: List[Dict], item_analysis: Dict,
                        threshold: float, analysis_stats: Dict):
        """Save final trade_cache.json for GitHub upload."""
        print(f"\n{'='*80}")
        print(f"SAVING FINAL RESULTS")
        print(f"{'='*80}")

        # Save raw 90d trade cache locally
        cache_file = CACHE_DIR / f"raw_90d_trades_{self.timestamp}.json"
        cache_data = {
            "metadata": {
                "timestamp": datetime.now().isoformat(),
                "window_days": MAX_DAYS_HISTORY,
                "total_trades": len(all_trades),
                "items_fetched": len(item_analysis),
                "api_url": API_URL,
                "volatility_threshold": threshold,
                "min_trades_threshold": MIN_TRADES_THRESHOLD,
                "analysis_stats": analysis_stats
            },
            "trades": all_trades,
            "item_analysis": item_analysis
        }

        with open(cache_file, 'w') as f:
            json.dump(cache_data, f, indent=2)

        cache_size = cache_file.stat().st_size / 1024 / 1024
        print(f"✓ Raw 90d cache (local): {cache_file.name}")
        print(f"  Size: {cache_size:.2f} MB")

        # Save final trade_cache.json for GitHub (same format as existing system)
        final_cache = {
            "metadata": {
                "last_updated": datetime.now().isoformat(),
                "total_trades": len(all_trades),
                "items_processed": len(item_analysis),
                "items_with_trades": len([k for k, v in item_analysis.items() if v['best_price'] > 0]),
                "source": "Local Analysis (Volatility-Aware 90d)",
                "api_url": API_URL,
                "volatility_threshold": threshold,
                "window_usage": analysis_stats['window_usage']
            },
            "trades": all_trades
        }

        with open(OUTPUT_TRADE_CACHE, 'w') as f:
            json.dump(final_cache, f, indent=2)

        final_size = OUTPUT_TRADE_CACHE.stat().st_size / 1024 / 1024
        print(f"✓ Final trade cache (for GitHub): {OUTPUT_TRADE_CACHE.relative_to(SCRIPT_DIR)}")
        print(f"  Size: {final_size:.2f} MB")

        # Save volatility analysis report
        report_file = SCRIPT_DIR / "analysis_90d_volatility_report.txt"
        with open(report_file, 'w') as f:
            f.write("="*80 + "\n")
            f.write("90-DAY VOLATILITY-AWARE ANALYSIS REPORT\n")
            f.write("="*80 + "\n")
            f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Analysis Window: Last {MAX_DAYS_HISTORY} days\n")
            f.write(f"\n")
            f.write(f"VOLATILITY PARAMETERS:\n")
            f.write(f"  Threshold: {threshold:.1f}%\n")
            f.write(f"  Minimum trades per window: {MIN_TRADES_THRESHOLD}\n")
            f.write(f"\n")
            f.write(f"DATA COLLECTION:\n")
            f.write(f"  Total trades: {len(all_trades):,}\n")
            f.write(f"  Items analyzed: {analysis_stats['total_analyzed']}\n")
            f.write(f"\n")
            f.write(f"WINDOW USAGE (90d data):\n")
            f.write(f"  1h window: {analysis_stats['window_usage']['1h']} items\n")
            f.write(f"  7d window: {analysis_stats['window_usage']['7d']} items\n")
            f.write(f"  90d window: {analysis_stats['window_usage']['90d']} items\n")
            f.write(f"\n")
            f.write(f"ITEM-BY-ITEM ANALYSIS:\n")
            f.write(f"{'='*80}\n")

            for item_name in sorted(item_analysis.keys()):
                analysis = item_analysis[item_name]
                f.write(f"\n{item_name}:\n")
                f.write(f"  Best Price: {analysis['best_price']:.2f} bags\n")
                f.write(f"  Window Used: {analysis['window_used']}\n")
                f.write(f"  Window Stats:\n")
                for window, stats in analysis['window_stats'].items():
                    f.write(f"    {window}: {stats['trades']} trades, avg {stats['price']:.2f} bags\n")

            f.write(f"\n{'='*80}\n")
            f.write(f"END OF REPORT\n")
            f.write(f"{'='*80}\n")

        report_size = report_file.stat().st_size / 1024
        print(f"✓ Volatility analysis report: {report_file.name}")
        print(f"  Size: {report_size:.2f} KB")

        print(f"\n{'='*80}")
        print(f"FINAL STEPS:")
        print(f"{'='*80}")
        print(f"1. Review {report_file.name} for detailed volatility analysis")
        print(f"2. Upload the following files to GitHub:")
        print(f"   - {OUTPUT_TRADE_CACHE.relative_to(SCRIPT_DIR)}")
        print(f"   - data/top_items.json (if not already uploaded)")
        print(f"3. GitHub Actions will run trade_economics_analysis.py automatically")
        print(f"{'='*80}\n")


async def main_async():
    """Main execution (async)."""
    print(f"\n{'*'*80}")
    print(f"LOCAL SCRIPT 2: 90-DAY FINAL DATA COLLECTION (ASYNC)")
    print(f"{'*'*80}\n")

    generator = FinalDataGenerator()

    # Load top items from Script 1
    item_names, threshold = generator.load_top_items()

    # Fetch 90-day trade data (concurrent)
    all_trades, fetch_results = await generator.fetch_90d_data(item_names, threshold)

    # Apply volatility-aware averaging
    item_analysis, analysis_stats = generator.apply_volatility_analysis(fetch_results, threshold)

    # Save final results
    generator.save_final_cache(all_trades, item_analysis, threshold, analysis_stats)

    print("✅ Script 2 complete! Final data ready for upload to GitHub.")


def main():
    """Main execution."""
    try:
        asyncio.run(main_async())
        return 0

    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        print(f"   Make sure you have run local_fetch_30d_analysis.py first")
        return 1

    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
